"""视频提示词档案 — 按 API 面（不是按公司名）。

shot_runner 的 _route_shot / adapter 消费本表。
Agnes 2.0 必须 passthrough=True，字段快照现行 builder 合同，不是官方英文六段式。
"""

from __future__ import annotations

from typing import Any

VIDEO_PROMPT_PROFILES: dict[str, dict[str, Any]] = {
    "seedance_25": {
        "api_id": "seedance_25",
        "language": "zh",
        "style": "narrative_timestamp",
        "max_chars": 4000,
        "required_fields": (),
        "negative": True,
        "seed": True,
        "duration_policy": {"kind": "range", "min": 4, "max": 30, "step": 1},
        "citation_syntax": "@图片N",
        "audio_syntax": "{台词}",
        "forbidden": ("【字幕】",),
        "models": [],
        "passthrough": False,
    },
    "seedance_20_pro": {
        "api_id": "seedance_20_pro",
        "language": "zh",
        "style": "narrative_timestamp",
        "max_chars": 2500,
        "required_fields": (),
        "negative": True,
        "seed": True,
        "duration_policy": {"kind": "range", "min": 4, "max": 15, "step": 1},
        "citation_syntax": "@图片N",
        "audio_syntax": "{台词}",
        "forbidden": ("【字幕】",),
        "models": [],
        "passthrough": False,
    },
    "jimeng_v30": {
        "api_id": "jimeng_v30",
        "language": "zh",
        "style": "jimeng_v30",
        "max_chars": 800,
        "required_fields": (),
        "negative": True,
        "seed": True,
        "duration_policy": {"kind": "enum", "values": [5, 10]},
        "citation_syntax": "",
        "audio_syntax": "",
        "forbidden": (),
        "models": [],
        "passthrough": False,
        "watermark_guard": "无字幕无文字无水印",
    },
    "kling_omni_30": {
        "api_id": "kling_omni_30",
        "language": "zh",
        "style": "omni_narrative",
        "max_chars": 2500,
        "required_fields": (),
        "negative": False,
        "seed": True,
        "duration_policy": {"kind": "range", "min": 3, "max": 15, "step": 1},
        "citation_syntax": "@image_N",
        "audio_syntax": "prompt_dialogue",
        "forbidden": (
            "【剧情】", "【全局音频】", "【台词】", "【音频锁定】",
            "<Picture", "<<<image_", "@图片",
        ),
        "models": [],
        "passthrough": False,
    },
    "kling_t2v_30": {
        "api_id": "kling_t2v_30",
        "language": "zh",
        "style": "omni_narrative",
        "max_chars": 2500,
        "required_fields": (),
        "negative": False,
        "seed": True,
        "duration_policy": {"kind": "range", "min": 3, "max": 15, "step": 1},
        "citation_syntax": "",
        "audio_syntax": "prompt_dialogue",
        "forbidden": (
            "【剧情】", "【全局音频】", "【台词】", "【音频锁定】",
            "<Picture", "<<<image_", "@图片",
        ),
        "models": [],
        "passthrough": False,
    },
    "kling_i2v_30": {
        "api_id": "kling_i2v_30",
        "language": "zh",
        "style": "i2v_motion",
        "max_chars": 2500,
        "required_fields": (),
        "negative": False,
        "seed": True,
        "duration_policy": {"kind": "range", "min": 3, "max": 15, "step": 1},
        "citation_syntax": "@主体名",
        "audio_syntax": "prompt_dialogue",
        "forbidden": (
            "【剧情】", "【全局音频】", "【台词】", "【音频锁定】",
            "<Picture", "<<<image_", "@图片",
        ),
        "models": [],
        "passthrough": False,
    },
    "kling_motion_30": {
        "api_id": "kling_motion_30",
        "language": "zh",
        "style": "i2v_motion",
        "max_chars": 2500,
        "required_fields": (),
        "negative": False,
        "seed": True,
        "duration_policy": {"kind": "none"},
        "citation_syntax": "",
        "audio_syntax": "",
        "forbidden": (
            "【剧情】", "【全局音频】", "【台词】", "【音频锁定】",
            "<Picture", "<<<image_", "@图片",
        ),
        "models": [],
        "passthrough": False,
    },
    "kling_image_omni": {
        "api_id": "kling_image_omni",
        "language": "zh",
        "style": "image_omni",
        "max_chars": 2500,
        "required_fields": (),
        "negative": False,
        "seed": True,
        "duration_policy": {"kind": "none"},
        "citation_syntax": "<<<image_N>>>",
        "audio_syntax": "",
        "forbidden": (
            "【剧情】", "【全局音频】", "<Picture", "@图片",
        ),
        "models": [],
        "passthrough": False,
    },
    "kling_i2v_21_pro": {
        "api_id": "kling_i2v_21_pro",
        "language": "zh",
        "style": "i2v_motion",
        "max_chars": 2500,
        "required_fields": (),
        "negative": True,
        "seed": True,
        "duration_policy": {"kind": "enum", "values": [5, 10]},
        "citation_syntax": "",
        "audio_syntax": "",
        "forbidden": ("【台词】", "【声音】", "【音频锁定】", "{", "}", "<<<image_"),
        "models": [],
        "passthrough": False,
    },
    "kling_v1": {
        "api_id": "kling_v1",
        "language": "zh",
        "style": "i2v_motion",
        "max_chars": 800,
        "required_fields": (),
        "negative": False,
        "seed": True,
        "duration_policy": {"kind": "enum", "values": [5, 10]},
        "citation_syntax": "",
        "audio_syntax": "",
        "forbidden": (),
        "models": [],
        "passthrough": False,
    },
    "agnes_v20": {
        "api_id": "agnes_v20",
        "language": "zh",
        "style": "agnes_sections",
        "max_chars": 3000,
        "required_fields": ("【台词】", "【声音】"),
        "negative": True,
        "seed": True,
        "duration_policy": {"kind": "enum", "values": [5, 10, 18]},
        "citation_syntax": "",
        "audio_syntax": "【台词】【音频锁定】",
        "forbidden": (),
        "models": ["agnes-video-v2.0"],
        "passthrough": True,
        "agnes_audio": True,
        "english_visual": False,
        "provider_max_chars": 3000,
        # 记录值：负面词实际已中文化（lib/prompt_english.py），全仓无消费者，保留不改值
        "negative_language": "en",
    },
    "agnes_v25": {
        "api_id": "agnes_v25",
        "language": "zh",
        "style": "agnes_v25",
        "max_chars": 3000,
        "required_fields": (),
        "negative": False,
        "seed": True,
        "duration_policy": {"kind": "range", "min": 4, "max": 12, "step": 1},
        "citation_syntax": "<Picture N>",
        "audio_syntax": "",
        "forbidden": (),
        "models": ["agnes-video-2.5-flash"],
        "passthrough": False,
    },
}


def prompt_profile(api_id: str) -> dict[str, Any]:
    raw = VIDEO_PROMPT_PROFILES.get(str(api_id or "").strip())
    if not raw:
        return {
            "api_id": str(api_id or ""),
            "language": "",
            "style": "",
            "max_chars": 0,
            "required_fields": (),
            "negative": False,
            "seed": False,
            "duration_policy": {"kind": "none"},
            "citation_syntax": "",
            "audio_syntax": "",
            "forbidden": (),
            "models": [],
            "passthrough": False,
        }
    out = dict(raw)
    policy = out.get("duration_policy")
    if isinstance(policy, dict):
        out["duration_policy"] = dict(policy)
    return out
